### PR TITLE
[Modify] Wrap Circles inside Group tag <g>

### PR DESCRIPTION
**Pull request by nielmo**
Wrap svg circles inside `<g>` tag. In order for the circles to not go below <foreignObject>

### CODE REVIEW

**Comment by genichiro** [comment]
LGTM!

we need bump version to 0.0.5 after this PR merged :)

**Comment by genichiro** [comment]
@nielmo Please fix conflicting files! Also you can remove dist/**.js files from this PR.

**Review by ghost — APPROVED** [review]
LGTM!
I'm sorry about my review was lated.
When conflict was resolved, I will merge this branch for master.

**Review by ghost — APPROVED** [review]
LTGM.
I'm sorry for my review was lated.
When conflict is resolved, I will merge this branch to master branch.

**Pull request merged**
